steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.6'
  displayName: 'Use Python $(python.version)'
- task: PythonScript@0
  inputs:
    scriptSource: 'inline'
    script: |
      print('Hello world 1')
      print('Hello world 2')